name: Setup Kubernetes
description: Sets up DO kube context

inputs:
  k8s_cluster_name:
    required: true
    description: "DOKS Cluster name"
  do_api_token:
    required: true
    description: "DigitalOcean API token"

runs:
  using: "composite"
  steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.do_api_token }}

    - name: Fetch kubeconfig
      shell: bash
      run: doctl kubernetes cluster kubeconfig save ${{ inputs.k8s_cluster_name }}
